name: Build Snapshots
on:
  push:
    branches: [ "mirai" ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ "mirai" ]
    paths-ignore:
      - '*.md'
permissions:
  contents: write
jobs:
  build:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Build Package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: deploy -Pdev.sha=${{ env.SHORT_SHA }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: qsign-${{ env.SHORT_SHA }}-all
          path: qsign-*-all.zip
          if-no-files-found: error
      - name: Upload to Release
        if: ${{ vars.NEED_TO_UPLOAD_RELEASE }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "qsign-*-all.zip"
          allowUpdates: true
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          tag: ${{ vars.UPLOAD_RELEASE_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
